### PR TITLE
Fix: Kaggle datasets download not working

### PR DESCRIPTION
**Pull request by BirajCoder**
- Added a few missing libraries in the requirements.txt file
- Kaggle dataset URLs now have "datasets/" in them. Replaced the "datasets/" with an empty string.
- "c" is changed to "competitions" on kaggle (fixed in kaggle_api.py file)
- Tried multiple datasets/competitions links to test the fix

### CODE REVIEW

**Comment by aakashns** [comment]
Looks fine to me. Can you share some links you have tested?

**Comment by aakashns** [comment]
Also, please increase the version number.

**Comment by BirajCoder** [comment]
> Looks fine to me. Can you share some links you have tested?

In the images below, the currently deployed version is on the left side. The fixed version and the files downloaded are on the right side.

This is for Kaggle Datasets. 
Link: https://www.kaggle.com/datasets/rupakroy/sonarcsv
image

The below one is a Kaggle competitions dataset. 
Link: https://www.kaggle.com/competitions/cascade-cup-22/data
image

**Comment by BirajCoder** [comment]
> Also, please increase the version number.

Updated the version number from 0.1.20  to 0.1.21.

**Comment by BirajCoder** [comment]
Updated the code with a corner case: If someone is using their old notebooks where the links of competitions have "c" instead of the new "competitions".

image

**Review by aakashns — APPROVED** [review]

**Pull request merged**
